### ISSUE TITLE
New web version not supported old browsers

### ISSUE THREAD

**Issue by ANTPro** [YouROK/TorrServer#139] opened 2022-01-13 17:41 UTC
New version MatriX.111 web gui not working in browsers on ipad air IOS 12.5 (Safari, Chrome v92.0.4515.90), but MUI support Chrome >= 90
(Новая версия MatriX.111 веб не работает в браузерах для ipad air IOS 12.5 (Safari, Chrome v92.0.4515.90), но в MUI заявлена поддержка Chrome >= 90)

**Comment by tsynik** [comment] 2022-01-14 05:07
> New version MatriX.111 web gui not working in browsers on ipad air IOS 12.5 (Safari, Chrome v92.0.4515.90), but MUI support Chrome >= 90 (Новая версия MatriX.111 веб не работает в браузерах для ipad air IOS 12.5 (Safari, Chrome v92.0.4515.90), но в MUI заявлена поддержка Chrome >= 90)

There is almost nothing changed in web gui in last 5? releases. Which version worked on ipad air IOS 12.5?

**Comment by ANTPro** [comment] 2022-01-14 08:40
1.0.77 - worked in Safari on IOS 12.5

**Comment by tsynik** [comment] 2022-01-14 08:47
> 1.0.77 - worked in Safari on IOS 12.5

1.x branch is not supported anymore. For MatriX use Firefox. This is duplicate of https://github.com/YouROK/TorrServer/issues/90, so closed. Reopen if Firefox doesn't works for you.

**Closed as completed by tsynik** 2022-01-14 08:47 UTC

**Comment by ANTPro** [comment] 2022-01-14 09:50
No Firefox for this iPad. Firefox need iOS 13

**Comment by ANTPro** [comment] 2022-01-14 09:55
In Chrome v90 i see web gui on 1 sec and next white page.

**Comment by tsynik** [comment] 2022-01-14 09:58
So, there is no lack for old iOS. You can try other alternatives or use any android phone or PC to access TorrServer web.
