### ISSUE TITLE
[BUG] Can't remove a torrent from the list via WEB

### ISSUE THREAD

**Issue by BrokVid** [YouROK/TorrServer#359] opened 2024-02-20 08:42 UTC
The home page fails to delete 1 particular torrent. Restarting the server did not help.
magnet link to it
magnet:?xt=urn:btih:594ca9364955d3412c21818729fe88dcbeb29e53&dn=The%20Good%20Place%20(2016-2019)%20BDRip%201080p

**To Reproduce**
1. Click DELETE
2. Click OK

**Expected behavior**
torrent deleted

**Desktop (please complete the following information):**
 - OS: Debian 12
 - TorrServer Version  MatriX.129

**Comment by filimonic** [comment] 2024-02-20 22:09
Unable to reproduce - torrent info does not load.

**Comment by tsynik** [comment] 2024-02-20 22:11
> The home page fails to delete 1 particular torrent. Restarting the server did not help.

It's expected behaviour with current release. Torrrent can't be removed if it have active reader for it. Try to Drop it in web interface before deletion.

**Comment by BrokVid** [comment] 2024-02-21 04:02
Drop didn't help, still can't delete it.
Yes and this server is used only by me, and at the moment I do not watch this series anywhere else.

**Comment by filimonic** [comment] 2024-02-21 08:35
Stop server, backup your `config.db` and remove the original one. Start server to create new config.db.
Can you repeat the problem with fresh config.db database?

**Comment by tsynik** [comment] 2024-02-21 08:49
It's not a question of DB. This commit add such behaviour https://github.com/YouROK/TorrServer/commit/068de3c56557045472860e74a18d74ba238a53b9 https://github.com/YouROK/TorrServer/commit/6ac8e1b84e67581f900fc8277070c5a5b686ab62

**Comment by tsynik** [comment] 2024-03-11 12:36
probably fixed with latest release https://github.com/YouROK/TorrServer/releases/tag/MatriX.130

**Closed as completed by tsynik** 2024-03-11 12:36 UTC
Labels: bug
