### ISSUE TITLE
[BUG] Build docker image

### ISSUE THREAD

**Issue by zainullinramil** [YouROK/TorrServer#443] opened 2024-08-16 09:23 UTC
https://github.com/YouROK/TorrServer/actions/runs/10065175871/job/27823691506

docker
buildx failed with: ERROR: failed to solve: process "/bin/sh -c apk add --update g++ && go run gen_web.go && cd server && go clean -i -r -cache && go mod tidy && go build -ldflags '-w -s' --o \"torrserver\" ./cmd" did not complete successfully: exit code: 1

**Comment by lexbritvin** [comment] 2024-08-16 09:43
Duplicate of #435
Fixed in https://github.com/YouROK/TorrServer/pull/441

**Closed as completed** 2024-08-16 10:43 UTC
Labels: bug
